### ISSUE TITLE
Potential Additions

### ISSUE THREAD

**Issue by chrisgrieser** [nathanlesage/hyperuniversity-site#1]
Hi, wonderful collection! I think this guide by Healy fits well into the website: https://plain-text.co/

A few months ago, I have written a guide probably also fits well into that collection:
https://www.notion.so/chrisgrieser/Comprehensive-Academic-Workflow-from-Reading-to-Writing-in-Markdown-a62298be91934043b11006be1ddc553a

**Comment by nathanlesage** [comment]
Your notion post is behind a login wall, so I can't add that. But I've added Healy's guide now! :)

**Comment by chrisgrieser** [comment]
Oh sorry, I shared the wrong URL – here is the post on a public URL: https://chris-grieser.de/Comprehensive-Academic-Workflow-from-Reading-to-Writing-in-Markdown
